/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RitualsIndexRouteImport } from './routes/rituals.index'
import { Route as RitualsSlugRouteImport } from './routes/rituals.$slug'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualsIndexRoute = RitualsIndexRouteImport.update({
  id: '/rituals/',
  path: '/rituals/',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualsSlugRoute = RitualsSlugRouteImport.update({
  id: '/rituals/$slug',
  path: '/rituals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bundles': typeof BundlesRoute
  '/contact': typeof ContactRoute
  '/policies': typeof PoliciesRoute
  '/story': typeof StoryRoute
  '/rituals/$slug': typeof RitualsSlugRoute
  '/rituals/': typeof RitualsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bundles': typeof BundlesRoute
  '/contact': typeof ContactRoute
  '/policies': typeof PoliciesRoute
  '/story': typeof StoryRoute
  '/rituals/$slug': typeof RitualsSlugRoute
  '/rituals': typeof RitualsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bundles': typeof BundlesRoute
  '/contact': typeof ContactRoute
  '/policies': typeof PoliciesRoute
  '/story': typeof StoryRoute
  '/rituals/$slug': typeof RitualsSlugRoute
  '/rituals/': typeof RitualsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bundles'
    | '/contact'
    | '/policies'
    | '/story'
    | '/rituals/$slug'
    | '/rituals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bundles'
    | '/contact'
    | '/policies'
    | '/story'
    | '/rituals/$slug'
    | '/rituals'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bundles'
    | '/contact'
    | '/policies'
    | '/story'
    | '/rituals/$slug'
    | '/rituals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BundlesRoute: typeof BundlesRoute
  ContactRoute: typeof ContactRoute
  PoliciesRoute: typeof PoliciesRoute
  StoryRoute: typeof StoryRoute
  RitualsSlugRoute: typeof RitualsSlugRoute
  RitualsIndexRoute: typeof RitualsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rituals/': {
      id: '/rituals/'
      path: '/rituals'
      fullPath: '/rituals/'
      preLoaderRoute: typeof RitualsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rituals/$slug': {
      id: '/rituals/$slug'
      path: '/rituals/$slug'
      fullPath: '/rituals/$slug'
      preLoaderRoute: typeof RitualsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BundlesRoute: BundlesRoute,
  ContactRoute: ContactRoute,
  PoliciesRoute: PoliciesRoute,
  StoryRoute: StoryRoute,
  RitualsSlugRoute: RitualsSlugRoute,
  RitualsIndexRoute: RitualsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
